### ISSUE TITLE
Apache Stops with Unknown Reason

### ISSUE THREAD

**Issue by FaikCoskun** [kdrypr/Unbound-Web-Interface#1]
When i added dns record to system, after a while apache stops. Can you resolve this issue?

**Comment by kdrypr** [comment]
Hi Faik,

Thanks for your submission. You can resolve this issue with adding a line to apache config file.

$sudo nano /etc/apache2/apache2.conf
add string to last line of config

Mutex posixsem

$ctrl - X and yes
$sudo service apache2 restart

**Comment by FaikCoskun** [comment]
Hi Kadir,
Thank you for your quick response and suggestion. I applied your suggestion, problem solved. Thanks
