### ISSUE TITLE
Security data

### ISSUE THREAD

**Issue by luciust** [kdrypr/Unbound-Web-Interface#2]
Hey, tested your project - works in a container, Ubuntu 24.04. 
There's one thing that needs options:
- information where to change the password for db in PHP file
- information that for the Web Interface you're using bcrypt with 10 rounds, so folks can change this password as well

**Comment by kdrypr** [comment]
Hi @luciust ,
Thank you for your support.
The changePassword function in core/functions.php does this.
You can change the number of rounds as you like.

**Comment by luciust** [comment]
Thanks - it's more of a suggestistion to add info to the install process README.md. It is already very detailed, so a good practice would be to give a novice user option to change passwords during installation - for both db access and web access.

**Comment by kdrypr** [comment]
thank you for your advice, normally we have not continued development but we can do this part.
